---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-styles-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-styles-cm
data:
  x-style.css: |
    .nav-bar__logo img {
      display: none;
    }
    .nav-bar__version::before {
      content: '';
    }
    .nav-bar__version {
      font-size: xx-small;
    }
    .nav-bar {
      background: #2975b4;
    }
    .nav-bar__item.active {
      border-color: #e0edeb;
    }
    .nav-bar__version::after {
      content: "devenv";
      display: block;
      color: #e0edeb;
    }