apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: devenv-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mikogs/project-template-envs.git
    path: devenv/grafana/
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-devenv.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devenv-grafana
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true