apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devenv-argocd
resources:
- argocd-styles-cm.yaml
- argocd-nodeport.yaml
- prometheus.yaml
- grafana.yaml
- devenv-node.yaml
- testenv-node.yaml
- devenv-frontend.yaml
- testenv-frontend.yaml
- ./../../../base
- fe-alex-expert.yaml
- fe-back-to-the-chopper.yaml
patchesStrategicMerge:
- argocd-cm.yaml
- argocd-server.yaml
- argocd-clusterrolebinding-argocd-application-controller.yaml
- argocd-clusterrolebinding-argocd-server.yaml
