---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testenv-node-region
  namespace: testenv-apps
spec:
  project: default
  source:
    repoURL: https://github.com/mikogs/project-template-envs.git
    path: testenv/node/overlays/testenv/region/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: testenv-apps
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testenv-node-region2
  namespace: testenv-apps
spec:
  project: default
  source:
    repoURL: https://github.com/mikogs/project-template-envs.git
    path: testenv/node/overlays/testenv/region2/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: testenv-apps
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testenv-node-region3
  namespace: testenv-apps
spec:
  project: default
  source:
    repoURL: https://github.com/mikogs/project-template-envs.git
    path: testenv/node/overlays/testenv/region3/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: testenv-apps
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
