apiVersion: v1
kind: Service
metadata:
  name: argocd-nodeport
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30201
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort