bases:
- ./../../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testenv-argocd
resources:
- argocd-styles-cm.yaml
- argocd-nodeport.yaml
- node.yaml
patchesStrategicMerge:
- argocd-cm.yaml
- argocd-server.yaml
- argocd-clusterrolebinding-argocd-application-controller.yaml
- argocd-clusterrolebinding-argocd-server.yaml